version: '3.6'
services:
  # jaeger
  core-test-jaeger: 
    environment:
      COLLECTOR_ZIPKIN_HTTP_PORT: 9411
    image: jaegertracing/all-in-one:1.6
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "9411:9411"
    restart: on-failure
  
  # php server
  core-test-php:
    # entrypoint: tail -f /dev/null
    depends_on:
      - core-test-jaeger
    build:
      context: .
    links:
      - core-test-jaeger
    ports:
      - "8000:8000"
    restart: on-failure
    volumes:
      - type: bind
        source: .
        target: /home/code