<?php
namespace App;

// use OpenCensus\Trace\Propagator\HttpHeaderPropagator;
use OpenCensus\Trace\Exporter\JaegerExporter;
//use OpenCensus\Trace\Exporter\LoggerExporter;
use OpenCensus\Trace\Integrations\Doctrine;
use OpenCensus\Trace\Integrations\Symfony;
use OpenCensus\Trace\Tracer;

use Monolog\Logger;

use Symfony\Component\HttpKernel\Bundle\Bundle as BaseBundle;

class MyLoger extends Logger {
    public function notice($message, array $context = array())
    {
        var_dump($message, $context);
        return parent::notice($message, $context); // TODO: Change the autogenerated stub
    }
}


class Bundle extends BaseBundle
{
    public function boot()
    {
        $this->setupOpenCensus();
    }

    private function setupOpenCensus()
    {
        if (php_sapi_name() == 'cli') {
            return;
        }

        // Enable OpenCensus extension integrations
        Doctrine::load();
        Symfony::load();

        // Start the request tracing for this request
//         $exporter = new LoggerExporter(new MyLoger('traces'));
        $exporter = new JaegerExporter('my-jaeger-php', [
            'host' => 'distributed-tracing-test-jaeger'
        ]);
        Tracer::start($exporter);
    }
}